name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick chromium-browser
    
    - name: Install npm dependencies
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      run: npm ci
    
    - name: Build extensions
      run: npm run build
      
    - name: Create placeholder icons for testing
      run: |
        mkdir -p dist/chrome/icons
        mkdir -p dist/firefox/icons
        mkdir -p dist/safari/icons
        
        # Create simple placeholder icons
        convert -size 16x16 xc:blue dist/chrome/icons/icon16.png
        convert -size 48x48 xc:blue dist/chrome/icons/icon48.png
        convert -size 128x128 xc:blue dist/chrome/icons/icon128.png
        
        cp dist/chrome/icons/* dist/firefox/icons/
        cp dist/chrome/icons/* dist/safari/icons/
        
    - name: Run tests with Puppeteer
      env:
        CI: 'true'
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      run: npm test
    
    - name: Upload extension artifacts
      uses: actions/upload-artifact@v4
      with:
        name: browser-extensions
        path: |
          dist/chrome/
          dist/firefox/
          dist/safari/
    
    - name: Upload screenshots
      uses: actions/upload-artifact@v4
      with:
        name: screenshots
        path: screenshots/